version: "3.9"

services:
  angular-app:
    image: node:20-alpine
    container_name: ngapp
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
